//
//  AcknowLocalizationTests.swift
//  AcknowExample
//
//  Created by Vincent Tourraine on 1/05/16.
//  Copyright © 2015-2016 VTourraine. All rights reserved.
//

import UIKit
import XCTest

@testable import AcknowList

class AcknowLocalizationTests: XCTestCase {

    func testLocalizedStringReturnsDefault() {

        class MockAcknowListViewController: AcknowListViewController {
            override class func preferredLanguageCode() -> String {
                return "qq-QQ"
            }
        }

        XCTAssertEqual("Acknowledgements", MockAcknowListViewController.localizedString(forKey: "VTAckAcknowledgements", defaultString: ""))
        XCTAssertEqual("Generated by CocoaPods", MockAcknowListViewController.localizedString(forKey: "VTAckGeneratedByCocoaPods", defaultString: ""))
    }

    func testLocalizedStringReturnsEnglish() {

        class MockAcknowListViewController: AcknowListViewController {
            override class func preferredLanguageCode() -> String {
                return "en-GB"
            }
        }

        XCTAssertEqual("Acknowledgements", MockAcknowListViewController.localizedString(forKey: "VTAckAcknowledgements", defaultString: ""))
        XCTAssertEqual("Generated by CocoaPods", MockAcknowListViewController.localizedString(forKey: "VTAckGeneratedByCocoaPods", defaultString: ""))
    }

    func testLocalizedStringReturnsEnglishUS() {

        class MockAcknowListViewController: AcknowListViewController {
            override class func preferredLanguageCode() -> String {
                return "en-US"
            }
        }

        XCTAssertEqual("Acknowledgements", MockAcknowListViewController.localizedString(forKey: "VTAckAcknowledgements", defaultString: ""))
        XCTAssertEqual("Generated by CocoaPods", MockAcknowListViewController.localizedString(forKey: "VTAckGeneratedByCocoaPods", defaultString: ""))
    }

    func testLocalizedStringReturnsFrenchForShortLanguageCode() {

        class MockAcknowListViewController: AcknowListViewController {
            override class func preferredLanguageCode() -> String {
                return "fr"
            }
        }

        XCTAssertEqual("Remerciements", MockAcknowListViewController.localizedString(forKey: "VTAckAcknowledgements", defaultString: ""))
        XCTAssertEqual("Généré par CocoaPods", MockAcknowListViewController.localizedString(forKey: "VTAckGeneratedByCocoaPods", defaultString: ""))
    }
    
    func testLocalizedStringReturnsFrench() {

        class MockAcknowListViewController: AcknowListViewController {
            override class func preferredLanguageCode() -> String {
                return "fr-FR"
            }
        }

        XCTAssertEqual("Remerciements", MockAcknowListViewController.localizedString(forKey: "VTAckAcknowledgements", defaultString: ""))
        XCTAssertEqual("Généré par CocoaPods", MockAcknowListViewController.localizedString(forKey: "VTAckGeneratedByCocoaPods", defaultString: ""))
    }

    func testLocalizedStringReturnsSimplifiedChinese() {

        class MockAcknowListViewController: AcknowListViewController {
            override class func preferredLanguageCode() -> String {
                return "zh-Hans"
            }
        }

        XCTAssertEqual("致谢", MockAcknowListViewController.localizedString(forKey: "VTAckAcknowledgements", defaultString: ""))
        XCTAssertEqual("使用 CocoaPods 生成", MockAcknowListViewController.localizedString(forKey: "VTAckGeneratedByCocoaPods", defaultString: ""))
    }
}
