//
//  AcknowParserTests.swift
//  AcknowExampleTests
//
//  Created by Vincent Tourraine on 15/08/15.
//  Copyright © 2015-2016 VTourraine. All rights reserved.
//

import UIKit
import XCTest

import AcknowList

class AcknowParserTests: XCTestCase {

    func testHeaderFooter() {
        let bundle = NSBundle(forClass: AcknowParserTests.self)
        let path = bundle.pathForResource("Pods-AcknowExampleTests-acknowledgements", ofType: "plist")
        if let path = path {
            let parser = AcknowParser(plistPath: path)
            XCTAssertNotNil(parser)

            let headerFooter = parser.parseHeaderAndFooter()
            if let header = headerFooter.header,
                let footer = headerFooter.footer {
                    XCTAssertEqual(header, "This application makes use of the following third party libraries:")
                    XCTAssertEqual(footer, "Generated by CocoaPods - http://cocoapods.org")
            }
            else {
                XCTAssert(false, "Header/footer not found")
            }
        }
        else {
            XCTAssert(false, "Plist not found")
        }
    }

    func testAcknowledgements() {
        let bundle = NSBundle(forClass: AcknowParserTests.self)
        let path = bundle.pathForResource("Pods-AcknowExampleTests-acknowledgements", ofType: "plist")
        if let path = path {
            let parser = AcknowParser(plistPath: path)
            XCTAssertNotNil(parser)

            let acknowledgements = parser.parseAcknowledgements()
            XCTAssertEqual(acknowledgements.count, 1)

            let acknow = acknowledgements.first
            if let acknow = acknow {
                XCTAssertEqual(acknow.title, "AcknowList")
                XCTAssertTrue(acknow.text.hasPrefix("Copyright (c) 2015-2016 Vincent Tourraine (http://www.vtourraine.net)"))
            }
            else {
                XCTAssert(false, "Acknowledgement not found")
            }
        }
        else {
            XCTAssert(false, "Plist not found")
        }
    }
    
    func testGeneralPerformance() {
        let bundle = NSBundle(forClass: AcknowParserTests.self)
        let path = bundle.pathForResource("Pods-AcknowExampleTests-acknowledgements", ofType: "plist")

        self.measureBlock() {
            if let path = path {
                let parser = AcknowParser(plistPath: path)
                parser.parseHeaderAndFooter()
                parser.parseAcknowledgements()
            }
        }
    }
    
}
