//
//  AcknowViewControllerTests.swift
//  AcknowExample
//
//  Created by Vincent Tourraine on 22/08/15.
//  Copyright © 2015-2016 VTourraine. All rights reserved.
//

import UIKit
import XCTest

import AcknowList

class AcknowViewControllerTests: XCTestCase {

    func testLoadView() {
        let acknow = Acknow(title: "Title", text: "Text...")
        let viewController = AcknowViewController(acknowledgement: acknow)
        viewController.loadView()

        XCTAssertEqual(viewController.title, "Title")
        XCTAssertEqual(viewController.textView!.text, "Text...")
    }
    
    func testLocalizedStringReturnsEnglish() {
        
        class MockAcknowListViewController: AcknowListViewController {
                        
            override class func preferredLanguageCode() -> String {
                return "en-GB"
            }
        }
        
        XCTAssertEqual("Acknowledgements", MockAcknowListViewController.localizedString(forKey: "VTAckAcknowledgements", defaultString: ""))
        
        XCTAssertEqual("Generated by CocoaPods", MockAcknowListViewController.localizedString(forKey: "VTAckGeneratedByCocoaPods", defaultString: ""))
    }
    
    func testLocalizedStringReturnsFrench() {
        
        class MockAcknowListViewController: AcknowListViewController {
            
            override class func preferredLanguageCode() -> String {
                return "fr-FR"
            }
        }
        
        XCTAssertEqual("Remerciements", MockAcknowListViewController.localizedString(forKey: "VTAckAcknowledgements", defaultString: ""))
        
        XCTAssertEqual("Généré par CocoaPods", MockAcknowListViewController.localizedString(forKey: "VTAckGeneratedByCocoaPods", defaultString: ""))
    }
    
    func testLocalizedStringReturnsSimplifiedChinese() {
        
        class MockAcknowListViewController: AcknowListViewController {
            
            override class func preferredLanguageCode() -> String {
                return "zh-Hans"
            }
        }
        
        XCTAssertEqual("致谢", MockAcknowListViewController.localizedString(forKey: "VTAckAcknowledgements", defaultString: ""))
        
        XCTAssertEqual("使用 CocoaPods 生成", MockAcknowListViewController.localizedString(forKey: "VTAckGeneratedByCocoaPods", defaultString: ""))
    }

}
